### ISSUE TITLE
Support Bard's `save_html` option

### ISSUE THREAD

**Issue by leonchris** [jacksleight/statamic-bard-texstyle#10]
## Bug Description
When you set save_html true in bard editor the content is correctly saved with the correct classes.
For example if you have a span with some class this is what it will be saved in content:
`<p><span class="text-danger">test</span></p>`

When you close the page and start editing again the content will lose all the styling and bard editor will render it as
`<p>test</p>`

And when you save it again the content will be stored as 
`<p>test</p>`

## How to Reproduce
Create a bard with the following blueprint: (the important step is to set `save_html: true`)
```
      -
        handle: content
        field:
          always_show_set_button: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - anchor
            - image
            - table
            - brand
          container: assets
          save_html: true
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: true
          fullscreen: true
          allow_source: true
          display: 'Content Blocks'
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          localizable: true
          max_items: 1
          read_only: false
```
Add the following config in bard_textstyle:
```
    'styles' => [

         'brand' => [
             'type'   => 'span',
             'name'   => 'Brand Text',
             'ident'  => 'B',
             'class'  => 'text-danger',
             'cp_css' => 'color: red;',
         ],

    ],
```

On editor use the brand text styling as shown and save and publish:![image](https://user-images.githubusercontent.com/15884915/165908778-61c93233-a865-4425-bfa9-bf365f91b517.png)

Check the content it should have something like that saved:
`<p><span class="text-danger">test</span></p>`

Close the page and reopen it to edit the content again:
![image](https://user-images.githubusercontent.com/15884915/165909309-761f33b3-07a1-460e-9a28-c40942b43fc9.png)

As you can see the style is gone and is not rendered correctly in bard editor.
Just save and publish the content again without typing something to the bard editor and you will see that the content is saved and lost all the styling properties:
`<p>test</p>`

## Environment

```
Statamic 3.3.9 Pro
Laravel 9.8.1
PHP 8.1.2
edalzell/forma 1.1
jacksleight/statamic-bard-mutator 1.1.0
jacksleight/statamic-bard-texstyle 1.0.1
simonhamp/gitamic 1.8.4
```
