### ISSUE TITLE
Invalid Content

### ISSUE THREAD

**Issue by mbs-arran-baker** [jacksleight/statamic-bard-texstyle#19]
## Bug Description
Bard field returning 'invalid content' after adding styles with type 'span'

## How to Reproduce
```
'brand' => [
    'type' => 'span',
    'name' => 'Brand Text',
    'ident' => 'B',
    'class' => 'brand-text',
    'cp_css' => 'color: dodgerblue; font-weight: 700',
],

'highlight-primary' => [
    'type' => 'span',
    'name' => 'Highlight Primary',
    'ident' => 'Hp',
    'icon' => 'square-solid',
    'class' => 'bg-primary'
],

```

Markdown in file. 

```
page_content_bard_field:
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bts_span
            attrs:
              class: brand-text
        text: 'Brand text'
```

## Extra Detail

---
![Screenshot 2023-01-31 at 15 45 45](https://user-images.githubusercontent.com/104069430/215807878-744aa674-4e52-4a54-86ce-109b41934e01.png)

## Environment

Environment
Application Name: skeleton-laravel-statamic
Laravel Version: 9.49.0
PHP Version: 8.1.14
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: skeleton-laravel-statamic.test/
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.1 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 2.0.0
spatie/statamic-responsive-images: 2.15.2
withcandour/aardvark-seo: 2.0.30
