### ISSUE TITLE
Control Panel CSS not applied when using image attributes

### ISSUE THREAD

**Issue by marcingajda** [jacksleight/statamic-bard-texstyle#89]
## Bug Description
Based on the documentation, the `cp_css` option should work when adding attributes to images ([link](https://jacksleight.dev/docs/bard-texstyle/attributes#feature-support)). However, it doesn't seem to work as expected: although the styles are generated, they contain mistakes (null in `.bard-content null[data-bts-attribute-width="75%"]`), and the `data-bts-attribute-width="75%"` attribute is missing from the image component in the editor (it should be probably added to the `[data-node-view-wrapper]`).

I guess the `null` in the styles happens, because there is no selector for images defined in `vendor/jacksleight/statamic-bard-texstyle/src/TypeManager.php`.

## How to Reproduce
In `config/statamic/bard_texstyle.php` define width attribute for image like this:

```php
    'attributes' => [
        'image' => [
            'width' => [
                'type' => 'select',
                'display' => 'Image size',
                'default' => '100%',
                'rendered' => false,
                'options' => [
                    '25%' => '25%',
                    '33%' => '33%',
                    '50%' => '50%',
                    '66%' => '66%',
                    '75%' => '75%',
                    '100%' => '100%'
                ],
                'cp_css' => [
                    '25%' => 'border: 10px solid red !important;',
                    '33%' => 'border: 10px solid red !important;',
                    '50%' => 'border: 10px solid red !important;',
                    '66%' => 'border: 10px solid red !important;',
                    '75%' => 'border: 10px solid red !important;',
                    '100%' => 'border: 10px solid red !important;',
                ],
            ],
        ],
    ]
```

Then set the width of an image using the attribute window and see that no styles are applied.

## Extra Detail
The generated styles:

```css
.bts-preview[data-bts-attribute-width="25%"], .bard-fieldtype-wrapper .bard-content null[data-bts-attribute-width="25%"] { border: 10px solid red !important; } 
.bts-preview[data-bts-attribute-width="33%"], .bard-fieldtype-wrapper .bard-content null[data-bts-attribute-width="33%"] { border: 10px solid red !important; } 
.bts-preview[data-bts-attribute-width="50%"], .bard-fieldtype-wrapper .bard-content null[data-bts-attribute-width="50%"] { border: 10px solid red !important; } 
.bts-preview[data-bts-attribute-width="66%"], .bard-fieldtype-wrapper .bard-content null[data-bts-attribute-width="66%"] { border: 10px solid red !important; } 
.bts-preview[data-bts-attribute-width="75%"], .bard-fieldtype-wrapper .bard-content null[data-bts-attribute-width="75%"] { border: 10px solid red !important; } 
.bts-preview[data-bts-attribute-width="100%"], .bard-fieldtype-wrapper .bard-content null[data-bts-attribute-width="100%"] { border: 10px solid red !important; }
```

Editor view:
![Image](https://github.com/user-attachments/assets/28b74116-8318-4bce-ac67-1e13b3de3959)

## Environment
Environment
Application Name: ...
Laravel Version: 11.44.2
PHP Version: 8.2.28
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: localhost:5000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 10
Sites: 3 (...)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.53.0 PRO

Statamic Addons
aerni/font-awesome: 3.0.2
eminos/statamic-iconify: 1.3.0
eminos/statamic-set-header-toggle: 1.1.0
eminos/statamic-tabs: 1.2.0
jacksleight/statamic-bard-mutator: 3.0.3
jacksleight/statamic-bard-texstyle: 3.5.2
ndx/statamic-bard-color-picker: 2.0.1
pecotamic/sitemap: 1.4.9
statamic/eloquent-driver: 4.21.0
stillat/relationships: 2.2.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: file
